### ISSUE TITLE
Is there a reason behind keeping redundant code?

### ISSUE THREAD

**Issue by softwarespot** [ljharb/is-equal#32]
Correct me if I am wrong, but once you get to this point in the code, aren't you guaranteed that the source and target are both the same data type, on account of comparing the internal class names?
```
if (!valIsBool) { return 'first argument is not a boolean; second argument is'; }
if (!otherIsBool) { return 'second argument is not a boolean; first argument is'; }

// ...

if (!valIsNumber) { return 'first argument is not a number; second argument is'; }
if (!otherIsNumber) { return 'second argument is not a number; first argument is'; }
```

If this is an oversight, then would you like me to submit a PR?

**Comment by ljharb** [comment]
No, because ES6 introduced `Symbol.toStringTag`, which changed `Object#toString` from reporting the "internal class" (which no longer exists) to reporting "a string value that the user can override". The user could have passed two values that have the same toStringTag, but are not in fact the same types.
