### ISSUE TITLE
use `files` property in package.json?

### ISSUE THREAD

**Issue by jonschlinkert** [ljharb/is-equal#34]
Looks like the npm package has some HTML files, `test/` dir and a few others included, which add up to about 4MB to the install. Not a big deal but increases install time and disk space for downstream consumers.

**Comment by ljharb** [comment]
Most assuredly never - the `files` property is incredibly dangerous, and only `.npmignore` should ever be used to exclude files from npm.

As for excluding files, `npm explore foo && npm install && npm test` should always work for every package, so tests should definitely be included.

As to "4MB", that's entirely false. You can see that the tests (https://unpkg.com/is-equal@1.5.3/test/) total up to less than 40K, and the entire package adds up to between 6-7K when I install it locally. Where did you get this number?

**Comment by jonschlinkert** [comment]
![image](https://cloud.githubusercontent.com/assets/383994/22311479/a11c8e1c-e321-11e6-829d-b926ea24ffeb.png)

**Comment by jonschlinkert** [comment]
My guess is that, since you aren't using something like `files` or `.npmignore`, (whichever doesn't matter to me), you have those files locally and they get packed up, but you're probably `.gitignore`ing them so they don't get committed.

care to share a link to some information about `files` or reasoning? I didn't realize it was dangerous, and if it is I'll stop using it on my own projects.

**Comment by ljharb** [comment]
OK, you're totally right about the html pages - I'm happy to exclude those. Not sure how I missed them.

The danger is just the human component - if you forget to add a new included file to "files", things will break in a way that's hard for the author to detect. If you forget to add a new ignored file to `.npmignore`, the only cost is "a slightly higher install size".

Download times are npm's concern, not package authors', and execution times are 100% unaffected (unless you're talking about `npm install` time, which is also an `npm` concern). Again, if you type `npm explore is-equal && npm install && npm test`, then absolutely you could use my project's test files, and that's an important use case.

I'm reopening this so that i can npmignore the `html` directory.

**Comment by ljharb** [comment]
(turns out i'd forgotten to gitignore my local `html` dir, that's not part of the repo and just for my local tests, and `npm` just grabs whatever git can see by default)

**Comment by ljharb** [comment]
I'll publish v1.5.4 shortly.
